  export default {
  AXOLOTL: require("../assets/profile_pics/AXOLOTL.webp"),
  BEAR: require("../assets/profile_pics/BEAR.webp"),
  CAT: require("../assets/profile_pics/CAT.webp"),
  DOG: require("../assets/profile_pics/DOG.webp"),
  EAGLE: require("../assets/profile_pics/EAGLE.webp"),
  FOX: require("../assets/profile_pics/FOX.webp"),
  FOX2: require("../assets/profile_pics/FOX2.webp"),
  FOX3: require("../assets/profile_pics/FOX3.webp"),
  HEDGEHOG: require("../assets/profile_pics/HEDGEHOG.webp"),
  OWL: require("../assets/profile_pics/OWL.webp"),
  OWL2: require("../assets/profile_pics/OWL2.webp"),
  PENGUIN: require("../assets/profile_pics/PENGUIN.webp"),
  PUFFIN: require("../assets/profile_pics/PUFFIN.webp"),
  RABBIT: require("../assets/profile_pics/RABBIT.webp"),
  RACCOON: require("../assets/profile_pics/RACCOON.webp"),
  REINDEER: require("../assets/profile_pics/REINDEER.webp"),
  SEAL: require("../assets/profile_pics/SEAL.webp"),
  WALRUS: require("../assets/profile_pics/WALRUS.webp"),
  RED_PANDA: require("../assets/profile_pics/RED_PANDA.webp"),
  KOALA: require("../assets/profile_pics/KOALA.webp"),
  SLOTH: require("../assets/profile_pics/SLOTH.webp"),
  LLAMA: require("../assets/profile_pics/LLAMA.webp"),
  OTTER: require("../assets/profile_pics/OTTER.webp"),
  FLAMING: require("../assets/profile_pics/FLAMINGO.webp"),
};
